### ISSUE TITLE
Architecture and Logic behind the module

### ISSUE THREAD

**Issue by southbeach** [mscdex/streamsearch#14]
Hi,

I did go through code and docs but can you please provide a high-level architecture or the inner workings to help us understand the approach?

Thanks.

**Comment by mscdex** [comment]
You're better off researching about the Boyer-Moore-Horspool algorithm, which this module uses. The remaining support code is straight forward enough.

**Comment by southbeach** [comment]
I researched on it but what's confusing for me is what is your take on searching the chunks where the boundary is split across two chunks (large files).

BMH: https://www.youtube.com/watch?v=PHXAOKQk2dw
