### ISSUE TITLE
Update new Buffer() to Buffer.from, Buffer.alloc

### ISSUE THREAD

**Issue by yahyaarshad** [mscdex/streamsearch#4]
Hi,
`sbmh.js` is using `new Buffer()` on several places. This way of creating buffer is deprecated due to memory leak vulnerability.  Can you please update the code. I had a fix but unable to push code to open pull request due to git hub restriction.

See: https://nodejs.org/api/buffer.html

**Comment by miguellaforet** [comment]
I'm also facing this problem.
Any news?

**Comment by euphbriggs** [comment]
@mscdex Are there any blockers from merging PR #5? I might be able to help if there's something that needs to be done.

**Comment by KerimG** [comment]
Yeah, also waiting for this to be merged in.

**Comment by ValterJunior** [comment]
I am also hoping this could be fixed

**Comment by Coding-Kiwi** [comment]
If anyone is here because of ssh2 / ssh2-streams, not streamsearch itself:

mscdex:
> The upcoming release doesn't use `ssh2-streams` anymore so it won't be an issue.
https://github.com/mscdex/ssh2/issues/932#issuecomment-727568229

**Comment by mscdex** [comment]
This is fixed in the recent codebase update.
